{{- if empty .Values.existingEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amphitrite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "amphitrite.labels" . | nindent 4 }}
type: Opaque
data:
  DB_CONNECTION_STRING: {{ required "A connection string to SQLServer is required" .Values.environment.dbConnectionString | b64enc }}
  ISSUER_KEY: {{ default (randAlphaNum 12) .Values.environment.issuerKey | b64enc }}
{{- end -}}