apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amphitrite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "amphitrite.labels" . }}
type: Secret
data:
  DB_CONNECTION_STRING: {{ .Values.environment.dbConnectionString }}
  ISSUER_KEY: {{ .Values.environment.issuerKey }}